### PR TITLE
New dependency on xserver-xorg-core-hwe for Xenial, blacklists and dependencies for new driver versions

### PR DESCRIPTION
**Pull request by bluca**
Fixes https://github.com/Bumblebee-Project/Bumblebee/issues/850

### CODE REVIEW

**Comment by htrex** [comment]
Thanks for the fix. I hope the merge and release on ppa will happen soon, as the current release can't be installed at all on Ubuntu 16.04.2.

**Comment by bluca** [comment]
@htrex I've pushed the changes tot he testing PPA, could you please give it a try and report back? Haven't got a Xenial install handy at the moment

**Comment by htrex** [comment]
thank you @bluca , I'll check it and report back!

**Comment by htrex** [comment]
@bluca sorry for the delay and thanks for the merge.
I can confirm that your commit fixed the issue, I was able to install bumblebee from testing repo on Ubuntu 16.04.2 with hwe.

Unhopefully I'm getting system freezes with bumblebee on my Dell XPS 9560 but that's another problem.
Even working on configs as described on varios guides I couldn't find a stable setup.
The problem is related to acpi support issues on the kernel level for this specific and recently released laptop I think.

Thank you again for your precious work.

**Comment by iamsiddhantsahu** [comment]
@bluca It helped, Thanks!

**Pull request merged**
